[package]
name = "vmtouch-rs"
version = "0.1.0"
authors = ["ocadaruma <ocadaruma@gmail.com>"]
edition = "2018"

[dependencies]
structopt = "0.3.23"
libc = "0.2.102"
log = "0.4.14"
env_logger = "0.9.0"
