name: CI

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
        - ubuntu-latest
        - macos-11
    steps:
    - name: Checkout sources
      uses: actions/checkout@v2
    - name: Install rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
    - name: Build
      run: cargo build
    - name: Lint
      run: cargo fmt --all -- --check
    - name: Clippy
      run: cargo clippy
    - name: Test
      run: cargo test
